# Generated by Django 3.1.4 on 2021-01-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Passport_size_photo.jpg', upload_to='home/vedant/PycharmProjects/Django_Project/mysite/pictures/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
