# Generated by Django 3.1.4 on 2021-01-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210109_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Passport_size_photo.jpg', upload_to='profile_pictures'),
        ),
    ]
