# Generated by Django 3.1.1 on 2020-10-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20201008_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://image.flaticon.com/icons/png/512/34/34754.png', max_length=600),
        ),
    ]
