# Generated by Django 3.1.1 on 2020-10-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.cleanpng.com%2Fpng-placeholder-icon-take-away-icon-food-and-restauran-7467313%2F&psig=AOvVaw0sI5hiRWqJHFBCMnebTZYU&ust=1602264825093000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNiOqOjNpuwCFQAAAAAdAAAAABAV', max_length=1000),
        ),
    ]
