# Generated by Django 3.1.1 on 2020-10-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20201009_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_img',
        ),
    ]
